### ISSUE TITLE
Transient CI errors with Docker image

### ISSUE THREAD

**Issue by ionutbalutoiu** [Microsoft/openenclave#1624]
There are some scenarios when the CI errors out with:

```
+ docker inspect -f . oetools:16.04
.
Failed to run image 'oetools:16.04'. Error:
````

Looking for more details into the full Jenkins console, I found this:

```
java.io.IOException: Failed to run image 'oetools:16.04'. Error: 
	at org.jenkinsci.plugins.docker.workflow.client.DockerClient.run(DockerClient.java:133)
	at org.jenkinsci.plugins.docker.workflow.WithContainerStep$Execution.start(WithContainerStep.java:184)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:268)
...
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

This has been uncounted at:

* [Bors-trying#794](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/793/pipeline/63)
* [Bors-staging#715](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/715/pipeline)
* [Bors-staging#716](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/716/pipeline)
* [Bors-staging#717](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/717/pipeline)
* [Bors-staging#718](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/718/pipeline)
* [Bors-staging#719](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/719/pipeline)
* [Bors-staging#720](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/720/pipeline)

**NOTE**: Some of the above `Bors-staging` blue ocean links do not show the error there, but the reason the job is failed is the same.

**Comment by ionutbalutoiu** [comment]
cc @johnkord @CodeMonkeyLeet for notifications on any progress to fix this problem.

**Comment by ionutbalutoiu** [comment]
As temporary workaround, I did a Docker cleanup on all the CI server. Hopefully the error won't pop up that often for now.

We'll try and get a proper fix for this.

**Comment by ionutbalutoiu** [comment]
Fixed with https://github.com/Microsoft/openenclave/pull/1695
